version: '3.4'

services:
  klipper-ulti:
    image: dimalo/klipper-moonraker
    build:
      dockerfile: ./klipper/Dockerfile
      context: .
      args:
        DEVICE_GROUP: device
        DEVICE_GID: 987
    container_name: klipper-ulti
    ports:
      - 7126:7125
    restart: unless-stopped
    volumes:
      - gcode_files:/home/klippy/gcode_files
      - ./config:/home/klippy/.config
      - moonraker_data:/home/klippy/.moonraker
      - ./ulti/printer.cfg:/home/klippy/.config/printer.cfg
      - ./ulti/macros:/home/klippy/.config/macros
    devices:
      - /dev/serial/by-id/usb-Klipper_lpc1768_77777-if00:/dev/serial/by-id/usb-Klipper_lpc1768_77777-if00

  klipper_ender:
    image: dimalo/klipper-moonraker
    build:
      dockerfile: ./klipper/Dockerfile
      context: .
      args:
        DEVICE_GROUP: device
        DEVICE_GID: 987
    container_name: klipper_ender
    ports:
      - 7127:7125
    restart: unless-stopped
    volumes:
      - gcode_files:/home/klippy/gcode_files
      - ./config:/home/klippy/.config
      - moonraker_data:/home/klippy/.moonraker
      - ./ender/printer.cfg:/home/klippy/.config/printer.cfg
    devices:
      - /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0:/dev/serial/by-id/usb-Klipper_stm32f103xe_30FFD9054246303712560657-if00

  klipper_ghost:
    image: dimalo/klipper-moonraker
    build:
      dockerfile: ./klipper/Dockerfile
      context: .
      args:
        DEVICE_GROUP: device
        DEVICE_GID: 987
    container_name: klipper_ghost
    ports:
      - 7128:7125
    restart: unless-stopped
    volumes:
      - gcode_files:/home/klippy/gcode_files
      - ./config:/home/klippy/.config
      - moonraker_data:/home/klippy/.moonraker
      - ./ghost/printer.cfg:/home/klippy/.config/printer.cfg
      - ./ghost/macros.cfg:/home/klippy/.config/macros.cfg
    devices:
      - /dev/ttyAMA1:/dev/ttyAMA1
  fluidd:
    image: cadriel/fluidd
    build:
      dockerfile: Dockerfile
      context: frontend
    container_name: fluidd
    ports:
      - 8010:80
    depends_on: 
      - klipper-ulti
    links:
      - klipper-ulti:klipper

  fluidd_ender:
    image: cadriel/fluidd
    container_name: fluidd_ender
    ports:
      - 8011:80
    depends_on: 
      - klipper_ender
    links:
      - klipper_ender:klipper
  
  fluidd_ghost:
    image: cadriel/fluidd
    container_name: fluidd_ghost
    ports:
      - 8012:80
    depends_on: 
      - klipper_ghost
    links:
      - klipper_ghost:klipper


  # mainsail:
  #   image: dimalo/mainsail
  #   build:
  #     dockerfile: Dockerfile
  #     context: frontend
  #     args:
  #       FRONTEND_ZIP_URL: https://github.com/meteyou/mainsail/releases/latest/download/mainsail.zip
  #   container_name: mainsail
  #   ports:
  #     - 8012:80
  #   depends_on: 
  #     - klipper
  #     # - klipper_another_printer
  #   links:
  #     - klipper:klipper
  #     # - klipper_another_printer:klipper_another_printer

volumes: 
  gcode_files:
  moonraker_data:

